/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jaffes_UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian MNA
 */
public class Buat_Laporan extends javax.swing.JFrame {

    /**
     * Creates new form Buat_Laporan
     */
    public Buat_Laporan() {
        initComponents();
        load_table();
        kosong();
        setLocationRelativeTo(this);
    }
    
    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Tanggal");
        model.addColumn("Total Keuntungan");
        
        //menampilkan data database kedalam tabel
        try {
            
            String sql = "select * from laporan";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
        }
    }
    
    private void kosong(){
        tanggaltxt.setText(null);
        totaltxt.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Kembaliitxt = new javax.swing.JButton();
        TambahUsertxt = new javax.swing.JButton();
        tanggaltxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        idtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buat Laporan");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 200, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Tanggal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Total Keuntungan");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 30));

        totaltxt.setBackground(new java.awt.Color(54, 33, 89));
        totaltxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        totaltxt.setForeground(new java.awt.Color(255, 255, 255));
        totaltxt.setBorder(null);
        totaltxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totaltxtMouseClicked(evt);
            }
        });
        totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltxtActionPerformed(evt);
            }
        });
        jPanel2.add(totaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 230, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 230, 20));

        Kembaliitxt.setBackground(new java.awt.Color(30, 139, 195));
        Kembaliitxt.setForeground(new java.awt.Color(255, 255, 255));
        Kembaliitxt.setText("Kembali");
        Kembaliitxt.setBorderPainted(false);
        Kembaliitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliitxtActionPerformed(evt);
            }
        });
        jPanel2.add(Kembaliitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 80, 40));

        TambahUsertxt.setBackground(new java.awt.Color(30, 139, 195));
        TambahUsertxt.setForeground(new java.awt.Color(255, 255, 255));
        TambahUsertxt.setText("Tambah");
        TambahUsertxt.setBorderPainted(false);
        TambahUsertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahUsertxtActionPerformed(evt);
            }
        });
        jPanel2.add(TambahUsertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 80, 40));

        tanggaltxt.setBackground(new java.awt.Color(54, 33, 89));
        tanggaltxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tanggaltxt.setForeground(new java.awt.Color(255, 255, 255));
        tanggaltxt.setBorder(null);
        tanggaltxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggaltxtMouseClicked(evt);
            }
        });
        tanggaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggaltxtActionPerformed(evt);
            }
        });
        jPanel2.add(tanggaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 230, 30));

        passwordtxt.setBackground(new java.awt.Color(54, 33, 89));
        passwordtxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordtxt.setBorder(null);
        passwordtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordtxtMouseClicked(evt);
            }
        });
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        jPanel2.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 220, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 220));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 790, 290));

        idtxt.setBackground(new java.awt.Color(54, 33, 89));
        idtxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        idtxt.setForeground(new java.awt.Color(255, 255, 255));
        idtxt.setBorder(null);
        idtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idtxtMouseClicked(evt);
            }
        });
        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 230, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totaltxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totaltxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltxtMouseClicked

    private void totaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltxtActionPerformed

    private void KembaliitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliitxtActionPerformed
        // TODO add your handling code here:
        Kasir_Transaksi katr = new Kasir_Transaksi();
        katr.setVisible(true);
        katr.pack();
        katr.setLocationRelativeTo(null);
        katr.setDefaultCloseOperation(Login_Page.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_KembaliitxtActionPerformed

    private void TambahUsertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahUsertxtActionPerformed

        try {
            String sql = "INSERT INTO laporan VALUES (null,'"+tanggaltxt.getText()+"','"+totaltxt.getText()+"')";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Membuat Laporan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_TambahUsertxtActionPerformed

    private void tanggaltxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggaltxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggaltxtMouseClicked

    private void tanggaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggaltxtActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String id =jTable1.getValueAt(baris, 0).toString();
        idtxt.setText(id);
        String tanggal =jTable1.getValueAt(baris, 1).toString();
        tanggaltxt.setText(tanggal);
        String totalkeuntungan = jTable1.getValueAt(baris,2).toString();
        totaltxt.setText(totalkeuntungan);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void idtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idtxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtMouseClicked

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void passwordtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordtxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtMouseClicked

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buat_Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buat_Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buat_Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buat_Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buat_Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembaliitxt;
    private javax.swing.JButton TambahUsertxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JTextField tanggaltxt;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
