/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jaffes_UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian MNA
 */
public class Dataku extends javax.swing.JFrame {

    /**
     * Creates new form Dataku
     */
    public Dataku() {
        initComponents();
        load_table();
        kosong();
        setLocationRelativeTo(this);
    }
    
    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nama Lengkap");
        model.addColumn("No HP");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Hak Akses");
        
        //menampilkan data database kedalam tabel
        try {
            
            String sql = "select * from user";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
        }
    }
    
    private void kosong(){
        namalengkaptxt.setText(null);
        nohptxt.setText(null);
        usernametxt.setText(null);
        passwordtxt.setText(null);  
        hakaksestxt.setSelectedItem(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        nohptxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        hakaksestxt = new javax.swing.JComboBox<>();
        Kembaliitxt = new javax.swing.JButton();
        TambahUsertxt = new javax.swing.JButton();
        HapusUsertxt = new javax.swing.JButton();
        EditUsertxt = new javax.swing.JButton();
        namalengkaptxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        idtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah Data");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 200, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nama Lengkap");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("No HP");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        nohptxt.setBackground(new java.awt.Color(54, 33, 89));
        nohptxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nohptxt.setForeground(new java.awt.Color(255, 255, 255));
        nohptxt.setBorder(null);
        nohptxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nohptxtMouseClicked(evt);
            }
        });
        nohptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohptxtActionPerformed(evt);
            }
        });
        jPanel2.add(nohptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 230, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Username");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        usernametxt.setBackground(new java.awt.Color(54, 33, 89));
        usernametxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(255, 255, 255));
        usernametxt.setBorder(null);
        usernametxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernametxtMouseClicked(evt);
            }
        });
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        jPanel2.add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 230, 20));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 30));

        passwordtxt.setBackground(new java.awt.Color(54, 33, 89));
        passwordtxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordtxt.setBorder(null);
        passwordtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordtxtMouseClicked(evt);
            }
        });
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        jPanel2.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 220, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 220, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Hak Akses");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, 30));

        hakaksestxt.setBackground(new java.awt.Color(0, 0, 102));
        hakaksestxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "KASIR", "PETUGAS", "KONSUMEN" }));
        hakaksestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakaksestxtActionPerformed(evt);
            }
        });
        jPanel2.add(hakaksestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 220, -1));

        Kembaliitxt.setBackground(new java.awt.Color(30, 139, 195));
        Kembaliitxt.setForeground(new java.awt.Color(255, 255, 255));
        Kembaliitxt.setText("Kembali");
        Kembaliitxt.setBorderPainted(false);
        Kembaliitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliitxtActionPerformed(evt);
            }
        });
        jPanel2.add(Kembaliitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 80, 40));

        TambahUsertxt.setBackground(new java.awt.Color(30, 139, 195));
        TambahUsertxt.setForeground(new java.awt.Color(255, 255, 255));
        TambahUsertxt.setText("Tambah");
        TambahUsertxt.setBorderPainted(false);
        TambahUsertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahUsertxtActionPerformed(evt);
            }
        });
        jPanel2.add(TambahUsertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 80, 40));

        HapusUsertxt.setBackground(new java.awt.Color(30, 139, 195));
        HapusUsertxt.setForeground(new java.awt.Color(255, 255, 255));
        HapusUsertxt.setText("Hapus");
        HapusUsertxt.setBorderPainted(false);
        HapusUsertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusUsertxtActionPerformed(evt);
            }
        });
        jPanel2.add(HapusUsertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 80, 40));

        EditUsertxt.setBackground(new java.awt.Color(30, 139, 195));
        EditUsertxt.setForeground(new java.awt.Color(255, 255, 255));
        EditUsertxt.setText("Edit");
        EditUsertxt.setBorderPainted(false);
        EditUsertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUsertxtActionPerformed(evt);
            }
        });
        jPanel2.add(EditUsertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 80, 40));

        namalengkaptxt.setBackground(new java.awt.Color(54, 33, 89));
        namalengkaptxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        namalengkaptxt.setForeground(new java.awt.Color(255, 255, 255));
        namalengkaptxt.setBorder(null);
        namalengkaptxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namalengkaptxtMouseClicked(evt);
            }
        });
        namalengkaptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namalengkaptxtActionPerformed(evt);
            }
        });
        jPanel2.add(namalengkaptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 230, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 220));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 790, 260));

        idtxt.setBackground(new java.awt.Color(54, 33, 89));
        idtxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        idtxt.setForeground(new java.awt.Color(255, 255, 255));
        idtxt.setText("adgjagh");
        idtxt.setBorder(null);
        idtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idtxtMouseClicked(evt);
            }
        });
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nohptxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nohptxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nohptxtMouseClicked

    private void nohptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohptxtActionPerformed

    private void usernametxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernametxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtMouseClicked

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void passwordtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordtxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtMouseClicked

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void hakaksestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakaksestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hakaksestxtActionPerformed

    private void TambahUsertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahUsertxtActionPerformed

        try {
            String sql = "INSERT INTO user VALUES (null,'"+namalengkaptxt.getText()+"','"+nohptxt.getText()+"','"+usernametxt.getText()+"','"+passwordtxt.getText()+"','"+hakaksestxt.getSelectedItem()+"')";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_TambahUsertxtActionPerformed

    private void HapusUsertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusUsertxtActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from user where no_hp='"+nohptxt.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_HapusUsertxtActionPerformed

    private void EditUsertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUsertxtActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE user SET id = '"+idtxt.getText()+"',Nama_lengkap = '"+namalengkaptxt.getText()+"', no_hp = '"+nohptxt.getText()+"', username= '"+usernametxt.getText()+"', password= '"+passwordtxt.getText()+"', hak_akses = '"+hakaksestxt.getSelectedItem()+"'WHERE id = '"+idtxt.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_EditUsertxtActionPerformed

    private void idtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idtxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String id =jTable1.getValueAt(baris, 0).toString();
        idtxt.setText(id);
        String namalengkap =jTable1.getValueAt(baris, 1).toString();
        namalengkaptxt.setText(namalengkap);
        String nohp = jTable1.getValueAt(baris,2).toString();
        nohptxt.setText(nohp);
        String username=jTable1.getValueAt(baris, 3).toString();
        usernametxt.setText(username);
        String password = jTable1.getValueAt(baris, 4).toString();
        passwordtxt.setText(password);
        String hakakses = jTable1.getValueAt(baris, 5).toString();
        hakaksestxt.setSelectedItem(hakakses);
    }//GEN-LAST:event_jTable1MouseClicked

    private void namalengkaptxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namalengkaptxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_namalengkaptxtMouseClicked

    private void namalengkaptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namalengkaptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namalengkaptxtActionPerformed

    private void KembaliitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliitxtActionPerformed
        // TODO add your handling code here:
        Admin_User adda = new Admin_User();
        adda.setVisible(true);
        adda.pack();
        adda.setLocationRelativeTo(null);
        adda.setDefaultCloseOperation(Login_Page.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_KembaliitxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dataku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dataku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dataku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dataku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dataku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditUsertxt;
    private javax.swing.JButton HapusUsertxt;
    private javax.swing.JButton Kembaliitxt;
    private javax.swing.JButton TambahUsertxt;
    private javax.swing.JComboBox<String> hakaksestxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namalengkaptxt;
    private javax.swing.JTextField nohptxt;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
