/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jaffes_UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian MNA
 */
public class Konsumen_Pesanan extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Konsumen_Pesanan
     */
    public Konsumen_Pesanan() {
        initComponents();
        setLocationRelativeTo(this);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tanggaltxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jumlahtxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nomejatxt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        TambahUsertxt1 = new javax.swing.JButton();
        Coffetxt = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        TambahUsertxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jaffes");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 20));

        jPanel3.setBackground(new java.awt.Color(64, 43, 100));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Beranda.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 170, 40));

        jPanel4.setBackground(new java.awt.Color(85, 65, 118));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon User.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pesan");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, 20));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 40));

        jPanel6.setBackground(new java.awt.Color(64, 43, 100));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon Paper.png"))); // NOI18N
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quisioner");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 170, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Logout");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 480));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 30));

        usernametxt.setBackground(new java.awt.Color(54, 33, 89));
        usernametxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(255, 255, 255));
        usernametxt.setBorder(null);
        usernametxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernametxtMouseClicked(evt);
            }
        });
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        jPanel1.add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 230, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 230, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Pesan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 30));

        tanggaltxt.setBackground(new java.awt.Color(54, 33, 89));
        tanggaltxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tanggaltxt.setForeground(new java.awt.Color(255, 255, 255));
        tanggaltxt.setBorder(null);
        tanggaltxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggaltxtMouseClicked(evt);
            }
        });
        tanggaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggaltxtActionPerformed(evt);
            }
        });
        jPanel1.add(tanggaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 230, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 230, 20));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Tanggal");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 30));

        jumlahtxt.setBackground(new java.awt.Color(54, 33, 89));
        jumlahtxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jumlahtxt.setForeground(new java.awt.Color(255, 255, 255));
        jumlahtxt.setBorder(null);
        jumlahtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumlahtxtMouseClicked(evt);
            }
        });
        jumlahtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahtxtActionPerformed(evt);
            }
        });
        jPanel1.add(jumlahtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 230, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 230, 20));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Jumlah");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("No Meja");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 30));

        nomejatxt.setBackground(new java.awt.Color(54, 33, 89));
        nomejatxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        nomejatxt.setForeground(new java.awt.Color(255, 255, 255));
        nomejatxt.setBorder(null);
        nomejatxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomejatxtMouseClicked(evt);
            }
        });
        nomejatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomejatxtActionPerformed(evt);
            }
        });
        jPanel1.add(nomejatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 230, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 230, 20));

        TambahUsertxt1.setBackground(new java.awt.Color(30, 139, 195));
        TambahUsertxt1.setForeground(new java.awt.Color(255, 255, 255));
        TambahUsertxt1.setText("Pesan");
        TambahUsertxt1.setBorderPainted(false);
        TambahUsertxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahUsertxt1ActionPerformed(evt);
            }
        });
        jPanel1.add(TambahUsertxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 80, 40));

        Coffetxt.setBackground(new java.awt.Color(0, 0, 102));
        Coffetxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Coffe", "ADMIN", "KASIR", "PETUGAS", "KONSUMEN" }));
        Coffetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffetxtActionPerformed(evt);
            }
        });
        jPanel1.add(Coffetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 230, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 610, 370));

        jPanel5.setBackground(new java.awt.Color(110, 89, 222));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Menu Pemesanan");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 160, 30));

        TambahUsertxt.setBackground(new java.awt.Color(30, 139, 195));
        TambahUsertxt.setForeground(new java.awt.Color(255, 255, 255));
        TambahUsertxt.setText("Lihat Menu");
        TambahUsertxt.setBorderPainted(false);
        TambahUsertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahUsertxtActionPerformed(evt);
            }
        });
        jPanel5.add(TambahUsertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 580, 60));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 610, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Konsumen_Dashboard koda = new Konsumen_Dashboard();
        koda.setVisible(true);
        koda.pack();
        koda.setLocationRelativeTo(null);
        koda.setDefaultCloseOperation(Login_Page.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Konsumen_Pesanan kope = new Konsumen_Pesanan();
        kope.setVisible(true);
        kope.pack();
        kope.setLocationRelativeTo(null);
        kope.setDefaultCloseOperation(Login_Page.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Konsumen_Quisioner koqu = new Konsumen_Quisioner();
        koqu.setVisible(true);
        koqu.pack();
        koqu.setLocationRelativeTo(null);
        koqu.setDefaultCloseOperation(Login_Page.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void usernametxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernametxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtMouseClicked

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void tanggaltxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggaltxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggaltxtMouseClicked

    private void tanggaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggaltxtActionPerformed

    private void jumlahtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahtxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahtxtMouseClicked

    private void jumlahtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahtxtActionPerformed

    private void nomejatxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomejatxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nomejatxtMouseClicked

    private void nomejatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomejatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomejatxtActionPerformed

    private void TambahUsertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahUsertxtActionPerformed

        Menu nume = new Menu();
        nume.setVisible(true);
        nume.pack();
        nume.setLocationRelativeTo(null);
        nume.setDefaultCloseOperation(Login_Page.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_TambahUsertxtActionPerformed

    private void TambahUsertxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahUsertxt1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO pesanan VALUES (null,'"+usernametxt.getText()+"','"+tanggaltxt.getText()+"','"+Coffetxt.getSelectedItem()+"','"+jumlahtxt.getText()+"','"+nomejatxt.getText()+"')";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Pesanan telah dikirim mohon tunggu sebentar");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_TambahUsertxt1ActionPerformed

    private void CoffetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoffetxtActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        Login_Page lopa = new Login_Page();
        lopa.setVisible(true);
        lopa.pack();
        lopa.setLocationRelativeTo(null);
        lopa.setDefaultCloseOperation(Login_Page.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konsumen_Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konsumen_Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konsumen_Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konsumen_Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Konsumen_Pesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Coffetxt;
    private javax.swing.JButton TambahUsertxt;
    private javax.swing.JButton TambahUsertxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jumlahtxt;
    private javax.swing.JTextField nomejatxt;
    private javax.swing.JTextField tanggaltxt;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
